name: CI
on: push
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        config:
          - { node: 11, chalk: 2 }
          - { node: 12, chalk: 3 }
          - { node: 13, chalk: 3 }
          - { node: 14, chalk: 4 }
        os: [macos-latest, ubuntu-latest]
        include:
          - config: { node: 11, chalk: 2 }
            os: windows-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.config.node }}
      - name: Node version
        run: node -v
      - name: Install chalk
        run: npm install -g chalk@${{ matrix.config.chalk }}
      - name: Chalk version
        run: npm list -g chalk